### ISSUE TITLE
Slackcat under python 3.5 in git bash/msysgit on Windows fails to find "slack" module

### ISSUE THREAD

**Issue by henhal** [nficano/slackcat#5]
```
$ slackcat
Traceback (most recent call last):
  File "c:\users\foo\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\foo\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\foo\AppData\Local\Programs\Python\Python35\Scripts\slackcat.exe\__main__.py", line 5, in <module>
  File "c:\users\foo\appdata\local\programs\python\python35\lib\site-packages\slackcat\__main__.py", line 8, in <module>
    import slack
ImportError: No module named 'slack'

```

**Comment by smn** [comment]
PR #4 fixes this

**Comment by Riduidel** [comment]
Is there a reason why this branch isn't yet merged ?

**Comment by smn** [comment]
🤷‍♂️

**Comment by Riduidel** [comment]
@nficano Are you still there ?
